apiVersion: v1
kind: Pod
metadata:
  name: cp-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "0.6"
      requests:
        cpu: "0.4"
    args:
    - -mem-total
    - 150Mi
    - -mem-alloc-size
    - 10Mi
    - -mem-alloc-sleep
    - 1s
    - -cpus
    - "2"
