apiVersion: v1
kind: Pod
metadata:
  name: kub
  labels:
    name: kub
    app: demo
spec:
  containers:
  - image: msrn/kub.v3
    imagePullPolicy: Always
    name: kub
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP