apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    app: demo
spec:
  containers:
  - image: docker.io/redis
    imagePullPolicy: Always
    name: redis
    ports:
    - containerPort: 6379
      protocol: TCP